### ISSUE TITLE
Unable to initialise referlist after providing required details

### ISSUE THREAD

**Issue by emmaadesile** [parthibanloganathan/referlist-sdk#3]
## Issue
Hi @parthibanloganathan, thanks for this awesome library. I just installed `referlist` for a react project I'm working on, but I haven't been able to get it running. This error message (screenshot below) shows up in the browser when I initialize it and I've added the `id`s for the email input and button . I tried it with hooks and class components. Any help will be appreciated.
## Expected Behavior
The package should work without any error

## Environment
Mac - Chome - Firefox

## Screenshot
<img width="1045" alt="Screenshot 2021-01-15 at 16 16 27" src="https://user-images.githubusercontent.com/26192691/104744358-11f06e80-574d-11eb-84ee-c238d3499543.png">

**Comment by parthibanloganathan** [comment]
Hey @emmaadesile can you try initializing it like this. I made a working example with Hooks:
```
import "./App.css";
import referlist from "referlist";
import React, { useEffect } from "react";

function App() {
  useEffect(() => {
    referlist.initialize({
      domain: "letterdrop",
      emailId: "referlistemail",
      buttonId: "referlistbutton"
    });
  }, []);

  return (
    <div className="App">
      <div>
        <input type="text" id="referlistemail" />
        <input type="button" id="referlistbutton" value="Join waitlist" />
      </div>
    </div>
  );
}

export default App;
```
Here's a video of the above in action:
https://www.loom.com/share/2293f1f2e55840d3b7a2e6bbb2496c22

**Comment by parthibanloganathan** [comment]
I've updated the docs as well https://docs.referlist.co/#/?id=install-in-react-or-nextjs-via-npm
