### ISSUE TITLE
Implementing on Next.js (Server Side Rendering)

### ISSUE THREAD

**Issue by eyaltoledano** [parthibanloganathan/referlist-sdk#4]
Hey there,

Running into an issue with a React / Next.js app where trying to initialize referlist in `componentDidMount` is returning an error about the window/document not being defined.

I usually get around this by defining a `if (typeof document !== 'undefined')` condition around it, but in this case it's still failing.

Going to attempt appending the script the old school way but your advice is appreciated

**Comment by mlevkovsky** [comment]
for nextjs you can use dynamic imports
For for example something like:
```
dynamic(
        () => import('referlist').then((referlist) => referlist.initialize({ domain: 'your_domain_here' })),
        { ssr: false}
    );
```

**Comment by parthibanloganathan** [comment]
Hi @eyaltoledano! @mlevkovsky is right. This SDK assumes it's running on a browser. You'll have to use dynamic imports to run this client-side. Here is a working code example:

```
import dynamic from "next/dynamic";

export default function Home() {
  const Referlist = dynamic(
    () =>
      import("referlist").then((referlist) =>
        referlist.initialize({ domain: "NAME_OF_YOUR_DOMAIN" })
      ),
    { ssr: false }
  );

  return (
    <div className="container">
      <Referlist />
      <div>
        <input type="text" id="referlistemail" />
        <input type="button" id="referlistbutton" value="Join waitlist" />
      </div>
    </div>
  );
}
```

For more reading, see:

- https://github.com/nzcodarnoc/korerorero-front-end/blob/main/src/components/ChatWidget.jsx
- https://medium.com/frontend-digest/why-is-window-not-defined-in-nextjs-44daf7b4604e

I will update the README with a NextJS example.
